import pathlib
nl=chr(10); dq=chr(34)
i4=" "*4; i8=" "*8; i12=" "*12
OUT=pathlib.Path(r"C:\Users\t.komurcu\sazabi\m6_slack\tests\test_m6.py")
L=[]
def w(*x): L.extend(x)
w(dq*3+"Sazabi M6 - Test Suite"+dq*3)
w("import sys,os,pathlib,pytest")
w("from unittest.mock import patch,MagicMock")
w("M6_DIR=pathlib.Path(__file__).parent.parent")
w("sys.path.insert(0,str(M6_DIR))")
w("import blocks,services,app as app_module")
w("","")
w("class TestBlocks:")
w(i4+"def test_status_ok(self):")
w(i8+"h={"+dq+"M2"+dq+":{"+dq+"status"+dq+":"+dq+"ok"+dq+"},"+dq+"M5"+dq+":{"+dq+"status"+dq+":"+dq+"down"+dq+"}}")
w(i8+"assert any("+dq+"ok"+dq+" in str(b) for b in blocks.status_blocks(h))")
w(i8+"assert any("+dq+"down"+dq+" in str(b) for b in blocks.status_blocks(h))")
w(i4+"def test_run_ok(self):")
w(i8+"r={"+dq+"sandbox_id"+dq+":"+dq+"x"+dq+","+dq+"command"+dq+":"+dq+"py"+dq+","+dq+"exit_code"+dq+":0,"+dq+"stdout"+dq+":"+dq+"2"+dq+","+dq+"stderr"+dq+":"+dq+dq+","+dq+"duration_ms"+dq+":5,"+dq+"status"+dq+":"+dq+"completed"+dq+"}")
w(i8+"assert any("+dq+"2"+dq+" in str(b) for b in blocks.run_blocks(r))")
w(i4+"def test_run_rejected(self):")
w(i8+"r={"+dq+"sandbox_id"+dq+":"+dq+"x"+dq+","+dq+"command"+dq+":"+dq+"rm"+dq+","+dq+"exit_code"+dq+":-1,"+dq+"stdout"+dq+":"+dq+dq+","+dq+"stderr"+dq+":"+dq+"[S]"+dq+","+dq+"duration_ms"+dq+":0,"+dq+"status"+dq+":"+dq+"rejected"+dq+"}")
w(i8+"assert any("+dq+"rejected"+dq+" in str(b).lower() for b in blocks.run_blocks(r))")
w(i4+"def test_error_block(self):")
w(i8+"assert any("+dq+"oops"+dq+" in str(b) for b in blocks.error_block("+dq+"oops"+dq+"))")
w(i4+"def test_alerts_empty(self):")
w(i8+"assert any("+dq+"No critical"+dq+" in str(b) for b in blocks.alerts_blocks([]))")
w(i4+"def test_alerts_critical(self):")
w(i8+"a=[{"+dq+"session_id"+dq+":"+dq+"s1"+dq+","+dq+"severity"+dq+":"+dq+"critical"+dq+","+dq+"msg"+dq+":"+dq+"DB down"+dq+"}]")
w(i8+"assert any("+dq+"critical"+dq+" in str(b).lower() or "+dq+"DB down"+dq+" in str(b) for b in blocks.alerts_blocks(a))")
w(i4+"def test_memory_blocks(self):")
w(i8+"tl={"+dq+"agent_id"+dq+":"+dq+"a1"+dq+","+dq+"total_steps"+dq+":1,"+dq+"summary"+dq+":"+dq+"ok"+dq+","+dq+"steps"+dq+":[{"+dq+"step_number"+dq+":1,"+dq+"action_type"+dq+":"+dq+"bash"+dq+","+dq+"result_summary"+dq+":"+dq+"ok"+dq+","+dq+"snapshots"+dq+":[]}]}")
w(i8+"assert any("+dq+"bash"+dq+" in str(b) for b in blocks.memory_blocks("+dq+"a1"+dq+",tl))")
w("","")
w("class TestSlashCommands:")
w(i4+"def test_status_command(self):")
w(i8+"say=MagicMock()")
w(i8+"with patch("+dq+"services.health_check_all"+dq+",return_value={"+dq+"M2"+dq+":{"+dq+"status"+dq+":"+dq+"ok"+dq+"}}):")
w(i12+"app_module._cmd_status(say)")
w(i12+"say.assert_called_once()")
w(i12+"assert "+dq+"blocks"+dq+" in say.call_args[1]")
w(i4+"def test_run_success(self):")
w(i8+"say=MagicMock()")
w(i8+"mr={"+dq+"sandbox_id"+dq+":"+dq+"x"+dq+","+dq+"command"+dq+":"+dq+"p"+dq+","+dq+"exit_code"+dq+":0,"+dq+"stdout"+dq+":"+dq+"2"+dq+","+dq+"stderr"+dq+":"+dq+dq+","+dq+"duration_ms"+dq+":5,"+dq+"status"+dq+":"+dq+"completed"+dq+"}")
w(i8+"with patch("+dq+"services.run_sandbox"+dq+",return_value=mr):")
w(i12+"app_module._cmd_run(say,"+dq+"python -c pass"+dq+")")
w(i12+"assert say.called")
w(i12+"assert any("+dq+"2"+dq+" in str(b) for b in say.call_args[1]["+dq+"blocks"+dq+"])")
w(i4+"def test_run_no_arg(self):")
w(i8+"say=MagicMock()")
w(i8+"app_module._cmd_run(say,"+dq+dq+")")
w(i8+"assert any("+dq+"Usage"+dq+" in str(b) or "+dq+"Error"+dq+" in str(b) for b in say.call_args[1]["+dq+"blocks"+dq+"])")
w(i4+"def test_memory_command(self):")
w(i8+"say=MagicMock()")
w(i8+"mt={"+dq+"agent_id"+dq+":"+dq+"a1"+dq+","+dq+"total_steps"+dq+":1,"+dq+"summary"+dq+":"+dq+"ok"+dq+","+dq+"steps"+dq+":[{"+dq+"step_number"+dq+":1,"+dq+"action_type"+dq+":"+dq+"bash"+dq+","+dq+"result_summary"+dq+":"+dq+"ok"+dq+","+dq+"snapshots"+dq+":[]}]}")
w(i8+"with patch("+dq+"services.get_agent_timeline"+dq+",return_value=mt):")
w(i12+"app_module._cmd_memory(say,"+dq+"a1"+dq+")")
w(i12+"assert say.called")
w(i4+"def test_alerts_command(self):")
w(i8+"say=MagicMock()")
w(i8+"with patch("+dq+"services.get_recent_alerts"+dq+",return_value=[]):")
w(i12+"app_module._cmd_alerts(say)")
w(i12+"assert say.called")
w("","")
w("class TestCriticalAlert:")
w(i4+"def test_send_alert_mocked(self):")
w(i8+"bolt_app=app_module.get_test_app()")
w(i8+"errs=[{"+dq+"msg"+dq+":"+dq+"DB down"+dq+","+dq+"severity"+dq+":"+dq+"critical"+dq+"}]")
w(i8+"with patch.object(bolt_app.client,"+dq+"chat_postMessage"+dq+",return_value={"+dq+"ok"+dq+":True}) as mp:")
w(i12+"r=app_module.send_critical_alert("+dq+"s1"+dq+",errs,channel="+dq+"#t"+dq+",bolt_app=bolt_app)")
w(i12+"assert r is True")
w(i12+"mp.assert_called_once()")
w(i12+"assert mp.call_args[1]["+dq+"channel"+dq+"]=="+dq+"#t"+dq)
w("","")
w("class TestServicesUnit:")
w(i4+"def test_health_dict(self):")
w(i8+"with patch("+dq+"services._get"+dq+",return_value={"+dq+"status"+dq+":"+dq+"ok"+dq+"}):")
w(i12+"assert len(services.health_check_all())>=2")
w(i4+"def test_run_sandbox(self):")
w(i8+"with patch("+dq+"services._post"+dq+",return_value={"+dq+"status"+dq+":"+dq+"completed"+dq+","+dq+"exit_code"+dq+":0}) as mp:")
w(i12+"r=services.run_sandbox("+dq+"python -c pass"+dq+")")
w(i12+"assert r["+dq+"status"+dq+"]=="+dq+"completed"+dq)
w(i12+"assert "+dq+"/sandbox/run"+dq+" in mp.call_args[0][0]")
w("","")
w("class TestResponseTime:")
w(i4+"def test_status_under_3s(self):")
w(i8+"import time; say=MagicMock()")
w(i8+"with patch("+dq+"services.health_check_all"+dq+",return_value={"+dq+"M2"+dq+":{"+dq+"status"+dq+":"+dq+"ok"+dq+"}}):")
w(i12+"t0=time.perf_counter(); app_module._cmd_status(say); dur=time.perf_counter()-t0")
w(i12+"assert dur<3.0")
w(i4+"def test_run_under_3s(self):")
w(i8+"import time; say=MagicMock()")
w(i8+"mr={"+dq+"sandbox_id"+dq+":"+dq+"x"+dq+","+dq+"command"+dq+":"+dq+"x"+dq+","+dq+"exit_code"+dq+":0,"+dq+"stdout"+dq+":"+dq+"2"+dq+","+dq+"stderr"+dq+":"+dq+dq+","+dq+"duration_ms"+dq+":5,"+dq+"status"+dq+":"+dq+"completed"+dq+"}")
w(i8+"with patch("+dq+"services.run_sandbox"+dq+",return_value=mr):")
w(i12+"t0=time.perf_counter(); app_module._cmd_run(say,"+dq+"python -c pass"+dq+"); dur=time.perf_counter()-t0")
w(i12+"assert dur<3.0")
w("","")
OUT.write_text(nl.join(L)+nl,"utf-8")
print("test_m6.py written, lines=",len(L))
