import pathlib
nl=chr(10)
dq=chr(34)
sq=chr(39)
i4=" "*4
i8=" "*8
i12=" "*12
i16=" "*16
OUT = pathlib.Path(r"C:\Users\t.komurcu\sazabi\m5_sandbox\tests\test_m5.py")
L = []
def w(*lines): L.extend(lines)
# imports + fixture
w(dq*3+"Sazabi M5 - Secure Sandbox Test Suite"+dq*3)
w("import sys, os, pathlib, uuid, json, pytest")
w("from unittest.mock import patch, MagicMock")
w("M5_DIR = pathlib.Path(__file__).parent.parent")
w("sys.path.insert(0, str(M5_DIR))")
w("from fastapi.testclient import TestClient")
w("import security, runner, webhook, api as api_mod")
w("", "")
w("@pytest.fixture")
w("def client():")
w(i4+"with TestClient(api_mod.app) as c:")
w(i8+"yield c")
w("", "")# TestWhitelist
w("class TestWhitelist:")
w(i4+"def test_allowed_python(self):")
w(i8+"security.validate_command(["+dq+"python"+dq+", "+dq+"-c"+dq+", "+dq+"pass"+dq+"])")
w(i4+"def test_reject_rm(self):")
w(i8+"with pytest.raises(security.SecurityError):")
w(i12+"security.validate_command(["+dq+"rm"+dq+", "+dq+"-rf"+dq+", "+dq+"/"+dq+"])")
w(i4+"def test_reject_curl(self):")
w(i8+"with pytest.raises(security.SecurityError):")
w(i12+"security.validate_command(["+dq+"curl"+dq+", "+dq+"http://evil.com"+dq+"])")
w(i4+"def test_reject_bash(self):")
w(i8+"with pytest.raises(security.SecurityError):")
w(i12+"security.validate_command(["+dq+"bash"+dq+", "+dq+"-c"+dq+", "+dq+"echo"+dq+"])")
w(i4+"def test_reject_empty(self):")
w(i8+"with pytest.raises(security.SecurityError):")
w(i12+"security.validate_command([])")
w(i4+"def test_reject_os_system(self):")
w(i8+"with pytest.raises(security.SecurityError, match="+dq+"Dangerous"+dq+"):")
w(i12+"security.validate_command(["+dq+"python"+dq+", "+dq+"-c"+dq+", "+dq+"import os; os.system("+sq+"ls"+sq+")"+dq+"])")
w("", "")# TestRunnerBasic
w("class TestRunnerBasic:")
w(i4+"def test_simple_run(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c "+sq+"print(1+1)"+sq+dq+")")
w(i8+"assert result["+dq+"exit_code"+dq+"] == 0")
w(i8+"assert "+dq+"2"+dq+" in result["+dq+"stdout"+dq+"]")
w(i4+"def test_exit_code_propagated(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c import sys; sys.exit(42)"+dq+")")
w(i8+"assert result["+dq+"exit_code"+dq+"] == 42")
w(i4+"def test_stderr_captured(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c import sys; sys.stderr.write("+sq+"err"+sq+")"+dq+")")
w(i8+"assert "+dq+"err"+dq+" in result["+dq+"stderr"+dq+"]")
w(i4+"def test_result_fields(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c pass"+dq+")")
w(i8+"for f in ["+dq+"sandbox_id"+dq+","+dq+"command"+dq+","+dq+"exit_code"+dq+","+dq+"stdout"+dq+","+dq+"stderr"+dq+","+dq+"duration_ms"+dq+","+dq+"resource_usage"+dq+","+dq+"status"+dq+"]:")
w(i12+"assert f in result, f"+dq+"Missing: {f}"+dq)
w(i4+"def test_sandbox_id_custom(self):")
w(i8+"sid = str(uuid.uuid4())")
w(i8+"result = runner.run_sandboxed("+dq+"python -c pass"+dq+", sandbox_id=sid)")
w(i8+"assert result["+dq+"sandbox_id"+dq+"] == sid")
w("", "")# TestSecurityEnforcement + TestTimeout
w("class TestSecurityEnforcement:")
w(i4+"def test_rm_rf_rejected(self):")
w(i8+"result = runner.run_sandboxed("+dq+"rm -rf /"+dq+")")
w(i8+"assert result["+dq+"status"+dq+"] == "+dq+"rejected"+dq)
w(i8+"assert result["+dq+"exit_code"+dq+"] == -1")
w(i8+"assert "+dq+"[SECURITY]"+dq+" in result["+dq+"stderr"+dq+"]")
w(i4+"def test_curl_rejected(self):")
w(i8+"result = runner.run_sandboxed("+dq+"curl http://evil.com"+dq+")")
w(i8+"assert result["+dq+"status"+dq+"] == "+dq+"rejected"+dq)
w(i4+"def test_os_system_rejected(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c import os; os.system("+sq+"ls"+sq+")"+dq+")")
w(i8+"assert result["+dq+"status"+dq+"] == "+dq+"rejected"+dq)
w(i4+"def test_rejected_no_stdout(self):")
w(i8+"result = runner.run_sandboxed("+dq+"bash -c echo pwned"+dq+")")
w(i8+"assert result["+dq+"status"+dq+"] == "+dq+"rejected"+dq)
w(i8+"assert result["+dq+"stdout"+dq+"] == "+dq+dq)
w("", "")
w("class TestTimeout:")
w(i4+"def test_timeout_kill(self):")
w(i8+"import importlib")
w(i8+"with patch.dict(os.environ, {"+dq+"SANDBOX_TIMEOUT"+dq+": "+dq+"2"+dq+"}):")
w(i12+"importlib.reload(runner)")
w(i12+"result = runner.run_sandboxed("+dq+"python -c while True: pass"+dq+")")
w(i12+"assert result["+dq+"status"+dq+"] == "+dq+"timeout"+dq)
w(i12+"assert result["+dq+"exit_code"+dq+"] == -9")
w(i12+"assert result["+dq+"duration_ms"+dq+"] < 10000")
w(i12+"importlib.reload(runner)")
w(i4+"def test_completes_before_timeout(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c pass"+dq+")")
w(i8+"assert result["+dq+"status"+dq+"] == "+dq+"completed"+dq)
w("", "")# TestFilesystem + TestAPI + TestWebhook + write file
w("class TestFilesystemIsolation:")
w(i4+"def test_write_path_inside_ok(self, tmp_path):")
w(i8+"box = str(tmp_path / "+dq+"sandbox_x"+dq+")")
w(i8+"pathlib.Path(box).mkdir()")
w(i8+"security.validate_write_path(str(tmp_path / "+dq+"sandbox_x"+dq+" / "+dq+"out.txt"+dq+"), box)")
w(i4+"def test_write_path_outside_raises(self, tmp_path):")
w(i8+"box = str(tmp_path / "+dq+"sandbox_x"+dq+")")
w(i8+"pathlib.Path(box).mkdir()")
w(i8+"with pytest.raises(security.SecurityError, match="+dq+"outside sandbox"+dq+"):")
w(i12+"security.validate_write_path("+dq+"/etc/passwd"+dq+", box)")
w(i4+"def test_run_uses_isolated_dir(self):")
w(i8+"result = runner.run_sandboxed("+dq+"python -c pass"+dq+")")
w(i8+"assert "+dq+"sandbox_dir"+dq+" in result")
w(i8+"assert "+dq+"sandbox_"+dq+" in result["+dq+"sandbox_dir"+dq+"]")
w("","")
w("class TestAPIEndpoints:")
w(i4+"def test_health(self, client):")
w(i8+"r = client.get("+dq+"/health"+dq+")")
w(i8+"assert r.status_code == 200 and r.json()["+dq+"status"+dq+"] == "+dq+"ok"+dq)
w(i4+"def test_run_ok(self, client):")
w(i8+"r = client.post("+dq+"/sandbox/run"+dq+", json={"+dq+"command"+dq+": "+dq+"python -c pass"+dq+", "+dq+"notify_webhook"+dq+": False})")
w(i8+"assert r.status_code == 200 and r.json()["+dq+"status"+dq+"] == "+dq+"completed"+dq)
w(i4+"def test_run_rejected(self, client):")
w(i8+"r = client.post("+dq+"/sandbox/run"+dq+", json={"+dq+"command"+dq+": "+dq+"rm -rf /"+dq+", "+dq+"notify_webhook"+dq+": False})")
w(i8+"assert r.json()["+dq+"status"+dq+"] == "+dq+"rejected"+dq)
w(i4+"def test_get_by_id(self, client):")
w(i8+"sid = str(uuid.uuid4())")
w(i8+"client.post("+dq+"/sandbox/run"+dq+", json={"+dq+"command"+dq+": "+dq+"python -c pass"+dq+", "+dq+"sandbox_id"+dq+": sid, "+dq+"notify_webhook"+dq+": False})")
w(i8+"r = client.get(f"+dq+"/sandbox/{sid}"+dq+")")
w(i8+"assert r.status_code == 200 and r.json()["+dq+"sandbox_id"+dq+"] == sid")
w(i4+"def test_unknown_id_404(self, client):")
w(i8+"assert client.get("+dq+"/sandbox/no-such-id-000"+dq+").status_code == 404")
w("","")
w("class TestWebhook:")
w(i4+"def test_no_url_skips(self):")
w(i8+"with patch.dict(os.environ, {"+dq+"M6_WEBHOOK_URL"+dq+": "+dq+dq+"}, clear=False):")
w(i12+"assert webhook.send_result({"+dq+"sandbox_id"+dq+": "+dq+"x"+dq+"}) is False")
w(i4+"def test_url_set_fires(self):")
w(i8+"with patch.dict(os.environ, {"+dq+"M6_WEBHOOK_URL"+dq+": "+dq+"http://localhost:9999/"+dq+"}):")
w(i12+"with patch("+dq+"webhook._post_json"+dq+") as mp:")
w(i16+"webhook.send_result({"+dq+"sandbox_id"+dq+": "+dq+"x"+dq+"})")
w(i16+"import time; time.sleep(0.1)")
w(i16+"mp.assert_called_once()")
w(i4+"def test_webhook_endpoint(self, client):")
w(i8+"r = client.post("+dq+"/webhook/sandbox-result"+dq+", json={"+dq+"sandbox_id"+dq+": "+dq+"wt"+dq+", "+dq+"status"+dq+": "+dq+"ok"+dq+"})")
w(i8+"assert r.status_code == 200 and r.json()["+dq+"received"+dq+"] is True")
w("","")
# write file
OUT.write_text(chr(10).join(L)+chr(10), "utf-8")
print("test_m5.py written, lines=", len(L))