import pathlib
nl=chr(10); dq=chr(34); sq=chr(39)
i4=b"\x20\x20\x20\x20".decode()
i8=b"\x20"*8; i12=b"\x20"*12
OUT=pathlib.Path(r"C:\Users\t.komurcu\sazabi\m6_slack\app.py")
L=[]
def w(*x): L.extend(x)# part 2: command functions (standalone - no app dependency)
w("def _cmd_status(say):")
w(i4+"say(blocks=blocks.status_blocks(services.health_check_all()))")
w("","")
w("def _cmd_run(say, command_str):")
w(i4+"if not command_str:")
w(i8.decode()+i4+"say(blocks=blocks.error_block("+dq+"Usage: /sazabi run <command>"+dq+"))); return")
w(i4+"say(blocks=blocks.run_blocks(services.run_sandbox(command_str)))")
w("","")
w("def _cmd_logs(say, session_id):")
w(i4+"if not session_id:")
w(i8.decode()+i4+"say(blocks=blocks.error_block("+dq+"Usage: /sazabi logs <session_id>"+dq+"))); return")
w(i4+"evts = services.get_session_logs(session_id)")
w(i4+"if not evts:")
w(i8.decode()+i4+"say(blocks=blocks.error_block(f"+dq+"No logs: {session_id}"+dq+"))); return")
w(i4+"lines = [e.get("+dq+"content"+dq+","+dq+dq+") for e in evts]")
w(i4+"say(blocks=blocks.logs_blocks(session_id, services.compress_logs_local(lines)))")
w("","")
w("def _cmd_memory(say, agent_id):")
w(i4+"if not agent_id:")
w(i8.decode()+i4+"say(blocks=blocks.error_block("+dq+"Usage: /sazabi memory <agent_id>"+dq+"))); return")
w(i4+"tl = services.get_agent_timeline(agent_id)")
w(i4+"if "+dq+"error"+dq+" in tl:")
w(i8.decode()+i4+"say(blocks=blocks.error_block(f"+dq+"Memory error: {tl.get(chr(39)errorchr(39),chr(39)+chr(39)?chr(39)+chr(39))}"+dq+"))); return")
w(i4+"say(blocks=blocks.memory_blocks(agent_id, tl))")
w("","")
w("def _cmd_alerts(say):")
w(i4+"say(blocks=blocks.alerts_blocks(services.get_recent_alerts()))")
w("","")# part 3: register + send_critical + write
w("def register_handlers(bolt_app):")
w(i4+"@bolt_app.command("+dq+"/sazabi"+dq+")")
w(i4+"def sazabi_command(ack, command, say):")
w(i8.decode()+i4+"ack()")
w(i8.decode()+i4+"text = (command.get("+dq+"text"+dq+") or "+dq+dq+").strip()")
w(i8.decode()+i4+"parts = text.split(None, 1)")
w(i8.decode()+i4+"sub = parts[0].lower() if parts else "+dq+"help"+dq)
w(i8.decode()+i4+"arg = parts[1].strip() if len(parts)>1 else "+dq+dq)
w(i8.decode()+i4+"try:")
w(i12.decode()+i4+"if sub=="+dq+"status"+dq+": _cmd_status(say)")
w(i12.decode()+i4+"elif sub=="+dq+"run"+dq+": _cmd_run(say, arg)")
w(i12.decode()+i4+"elif sub=="+dq+"logs"+dq+": _cmd_logs(say, arg)")
w(i12.decode()+i4+"elif sub=="+dq+"memory"+dq+": _cmd_memory(say, arg)")
w(i12.decode()+i4+"elif sub=="+dq+"alerts"+dq+": _cmd_alerts(say)")
w(i12.decode()+i4+"else: say(blocks=blocks.status_blocks(services.health_check_all()))")
w(i8.decode()+i4+"except Exception as e:")
w(i12.decode()+i4+"logger.exception(f"+dq+"/{sub} failed"+dq+")")
w(i12.decode()+i4+"say(blocks=blocks.error_block(f"+dq+"Error: {e}"+dq+"))")
w("","")
w("def send_critical_alert(session_id, errors, channel=None, bolt_app=None):")
w(i4+"target = channel or cfg.SLACK_ALERT_CHANNEL")
w(i4+"client = (bolt_app or get_app()).client")
w(i4+"try:")
w(i8.decode()+i4+"client.chat_postMessage(channel=target,")
w(i12.decode()+i4+"blocks=blocks.critical_alert_blocks(session_id, errors),")
w(i12.decode()+i4+"text=f"+dq+"CRITICAL: {len(errors)} error(s) in {session_id}"+dq+")")
w(i8.decode()+i4+"return True")
w(i4+"except Exception as e:")
w(i8.decode()+i4+"logger.warning(f"+dq+"Alert failed: {e}"+dq+")")
w(i8.decode()+i4+"return False")
w("","")
w("if __name__ == "+dq+"__main__"+dq+":")
w(i4+"bolt_app = get_app()")
w(i4+"register_handlers(bolt_app)")
w(i4+"bolt_app.start(port=int(os.getenv("+dq+"SLACK_PORT"+dq+","+dq+"3000"+dq+")))")
OUT.write_text(nl.join(L)+nl,"utf-8")
print("app.py written, lines=",len(L))