import pathlib
p=pathlib.Path(r"C:\Users\t.komurcu\sazabi\m3_compression\compressor.py")
existing=p.read_text("utf-8")
lines=[]
lines.append(chr(34)*3+"Sazabi M3 - Claude API compressor."+chr(34)*3)
lines.append("import os, json, time, threading, logging, re")
lines.append("from typing import List, Dict, Any, Optional")
lines.append("from dataclasses import dataclass, field")
lines.append("")
lines.append("logger = logging.getLogger("+chr(34)+"sazabi.m3.compressor"+chr(34)+")")
lines.append("MODEL = "+chr(34)+"claude-haiku-4-5"+chr(34))
lines.append("MAX_CALLS_PER_MINUTE = 10")
lines.append("MAX_RETRIES = 3")
lines.append("BASE_BACKOFF = 1.0")
lines.append("COST_PER_1M_INPUT = 0.80")
lines.append("COST_PER_1M_OUTPUT = 4.00")
lines.append("SYSTEM_PROMPT = ("+chr(10)+chr(32)*4+chr(34)+"Sen bir DevOps asistanisin. Sana verilen log satirlarini analiz et. SADECE JSON dondurmeli."+chr(34)+chr(10)+")")
lines.append("")
header=chr(10).join(lines)+chr(10)
p.write_text(header+existing,"utf-8")
print("ok, total=",len(header)+len(existing))